### PR TITLE
Updating the method for loading in curator settings

### PR DESCRIPTION
**Pull request by ewolinetz**
to use yaml instead of json

### CODE REVIEW

**Comment by ewolinetz** [comment]
TODO: need to clean up vestigial JSON code and add to documentation on how to create settings and mount to DC

**Comment by richm** [comment]
minor nit, otherwise, lgtm

**Comment by ewolinetz** [comment]
@richm updated docs, removed old json related code items and addressed nits.  if still looks good, we can merge away

**Comment by richm** [comment]
merged

**Pull request closed without merging**
